server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
        format_sql: 'FALSE'
        show_sql: 'FALSE'
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"