server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
        format_sql: 'FALSE'
        show_sql: 'FALSE'
    hibernate:
      ddl-auto: update
