version: '3.8'

services:
  mysql:
    image: mysql
    container_name: MySQL
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'bw_admin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: RabbitMQ
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  mysql:
  rabbitmq_data:
  rabbitmq_logs: